#!/bin/sh
cat - |sed '
s="ISO 8879:1986//ENTITIES Added Latin 1//EN"="ISO 8879:1986//ENTITIES Added Latin 1 SGML//EN"=
s="ISO 8879:1986//ENTITIES Added Latin 2//EN"="ISO 8879:1986//ENTITIES Added Latin 2 SGML//EN"=
s="ISO 8879:1986//ENTITIES Diacritical Marks//EN"="ISO 8879:1986//ENTITIES Diacritical Marks SGML//EN"=
s="ISO 8879:1986//ENTITIES Box and Line Drawing//EN"="ISO 8879:1986//ENTITIES Box and Line Drawing SGML//EN"=
s="ISO 8879:1986//ENTITIES Numeric and Special Graphic//EN"="ISO 8879:1986//ENTITIES Numeric and Special Graphic SGML//EN"=
s="ISO 8879:1986//ENTITIES Publishing//EN"="ISO 8879:1986//ENTITIES Publishing SGML//EN"=
s="ISO 8879:1986//ENTITIES General Technical//EN"="ISO 8879:1986//ENTITIES General Technical SGML//EN"=
s="ISO 8879:1986//ENTITIES Added Math Symbols: Arrow Relations//EN"="ISO 8879:1986//ENTITIES Added Math Symbols: Arrow Relations SGML//EN"=
s="ISO 8879:1986//ENTITIES Added Math Symbols: Binary Operators//EN"="ISO 8879:1986//ENTITIES Added Math Symbols: Binary Operators SGML//EN"=
s="ISO 8879:1986//ENTITIES Added Math Symbols: Delimiters//EN"="ISO 8879:1986//ENTITIES Added Math Symbols: Delimiters SGML//EN"=
s="ISO 8879:1986//ENTITIES Added Math Symbols: Negated Relations//EN"="ISO 8879:1986//ENTITIES Added Math Symbols: Negated Relations SGML//EN"=
s="ISO 8879:1986//ENTITIES Added Math Symbols: Ordinary//EN"="ISO 8879:1986//ENTITIES Added Math Symbols: Ordinary SGML//EN"=
s="ISO 8879:1986//ENTITIES Added Math Symbols: Relations//EN"="ISO 8879:1986//ENTITIES Added Math Symbols: Relations SGML//EN"=
s="ISO 8879:1986//ENTITIES Greek Letters//EN"="ISO 8879:1986//ENTITIES Greek Letters SGML//EN"=
s="ISO 8879:1986//ENTITIES Monotoniko Greek//EN"="ISO 8879:1986//ENTITIES Monotoniko Greek SGML//EN"=
s="ISO 8879:1986//ENTITIES Greek Symbols//EN"="ISO 8879:1986//ENTITIES Greek Symbols SGML//EN"=
s="ISO 8879:1986//ENTITIES Alternative Greek Symbols//EN"="ISO 8879:1986//ENTITIES Alternative Greek Symbols SGML//EN"=
s="ISO 8879:1986//ENTITIES Russian Cyrillic//EN"="ISO 8879:1986//ENTITIES Russian Cyrillic SGML//EN"=
s="ISO 8879:1986//ENTITIES Non-Russian Cyrillic//EN"="ISO 8879:1986//ENTITIES Non-Russian Cyrillic SGML//EN"=
'
